const express = require('express');
const router = express.Router();
const { db } = require('../db/connection');
const { getLevelInfo, getTreeStage, todayIso, syncStreakShields } = require('../lib/gamification');
const { quoteOfTheDay } = require('../lib/ai');

router.get('/', async (req, res) => {
  try {
    const userId = req.user.id;
// In the dashboard route, accept date from query
const today = req.query.date || new Date().toISOString().slice(0, 10);
    // project_id IS NULL everywhere here — tasks generated by a
    // project's "Break into tasks" belong on that project's card only,
    // not in the general Today's Tasks / Coming Up / progress counts.
    // source != 'nuvora' everywhere here — the self-seeded birthday
    // entry (see notifications.js's ensureBirthdayTask) isn't a real
    // to-do, so it shouldn't count toward "X left today", the
    // productivity score, or crowd the generic Coming Up list. It gets
    // its own dedicated query/card below instead.
    const [todaysTasksResult, habitsResult, upcomingResult, moodResult, tasksDoneResult, totalTasksResult, birthdayResult, nextMilestonesResult] = await Promise.all([
      // priority is TEXT ('low'|'medium'|'high') — a plain
      // `ORDER BY priority DESC` sorts alphabetically (medium, low,
      // high), not by actual urgency. The CASE maps it to a real rank so
      // high-priority tasks genuinely show up first in Today's Tasks.
      // Pending tasks (todo/doing) keep the original filter — due today,
      // or no deadline at all (an undated "someday" bucket, shown until
      // done). Done tasks are new here (used to be excluded entirely) —
      // scoped tightly to "finished today" via completed_at, not the
      // original deadline, so the Dashboard's Done column shows what was
      // actually accomplished today without dragging in old completed
      // work that happened to be due today weeks ago. LIMIT raised from
      // 6 → 24 now that this feeds a 3-column board (Not Started/In
      // Progress/Done) instead of one flat list.
      db.execute({
        sql: `SELECT * FROM tasks
              WHERE user_id = ? AND project_id IS NULL AND source != 'nuvora'
                AND (
                  (status != 'done' AND (deadline = ? OR deadline IS NULL))
                  OR (status = 'done' AND date(completed_at) = ?)
                )
              ORDER BY CASE priority WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END DESC
              LIMIT 24`,
        args: [userId, today, today],
      }),
      db.execute({ sql: `SELECT * FROM habits WHERE user_id = ?`, args: [userId] }),
      db.execute({ sql: `SELECT * FROM tasks WHERE user_id = ? AND status != 'done' AND project_id IS NULL AND source != 'nuvora' AND deadline IS NOT NULL AND deadline >= ? ORDER BY deadline ASC LIMIT 5`, args: [userId, today] }),
      db.execute({ sql: `SELECT * FROM moods WHERE user_id = ? AND date = ?`, args: [userId, today] }),
      // "done" here has to mean the same thing as the denominator below
      // (deadline = today) — matching on completed_at date instead made a
      // task done yesterday but due today count toward the total without
      // ever counting as done, showing e.g. "0/1" for an already-finished task.
      db.execute({ sql: `SELECT COUNT(*) c FROM tasks WHERE user_id = ? AND status='done' AND project_id IS NULL AND source != 'nuvora' AND deadline = ?`, args: [userId, today] }),
      db.execute({ sql: `SELECT COUNT(*) c FROM tasks WHERE user_id = ? AND project_id IS NULL AND source != 'nuvora' AND deadline = ?`, args: [userId, today] }),
      db.execute({ sql: `SELECT title, deadline FROM tasks WHERE user_id = ? AND source = 'nuvora' AND category = 'Birthday' LIMIT 1`, args: [userId] }),
      // Next concrete step per active goal — the lowest-position
      // not-done milestone in each goal, not just "all incomplete
      // milestones," so a goal with 8 milestones doesn't crowd out
      // every other goal's turn. scheduled_date is opt-in (the
      // final-week day planner) so most milestones won't have one —
      // dated ones surface first since they're time-sensitive, then
      // the rest fill in by how recently the goal was created.
      db.execute({
        sql: `SELECT m.id, m.title, m.scheduled_date, g.id AS goal_id, g.title AS goal_title
              FROM milestones m
              JOIN goals g ON g.id = m.goal_id
              WHERE g.user_id = ? AND g.status = 'active' AND m.done = 0
                AND m.id = (
                  SELECT m2.id FROM milestones m2
                  WHERE m2.goal_id = m.goal_id AND m2.done = 0
                  ORDER BY m2.position ASC LIMIT 1
                )
              ORDER BY (m.scheduled_date IS NULL) ASC, m.scheduled_date ASC, g.created_at DESC
              LIMIT 5`,
        args: [userId],
      }),
    ]);

    const habits = habitsResult.rows;
    const todaysHabits = await Promise.all(habits.map(async (h) => {
      const r = await db.execute({ sql: `SELECT 1 FROM habit_logs WHERE habit_id = ? AND date = ?`, args: [h.id, today] });
      return { ...h, doneToday: !!r.rows[0] };
    }));

    const tasksDoneToday = Number(tasksDoneResult.rows[0].c);
    const totalTasksToday = Number(totalTasksResult.rows[0].c);
    const habitsDoneToday = todaysHabits.filter((h) => h.doneToday).length;
    const totalHabitsToday = habits.length;

    // Real bug that used to live here: the 0.6/0.4 task/habit weighting
    // was fixed regardless of whether one side even had anything to
    // measure. On a day with zero tasks due but every habit checked off,
    // taskScore is 0 (not skipped, just zero out of zero) and the score
    // capped at habitScore * 0.4 = 40% — a perfect day showing as barely
    // faring, with the missing 60% attributed to a dimension that never
    // had anything due in the first place. Same the other way for a
    // day with no habits at all. The weight now only splits 0.6/0.4 when
    // BOTH dimensions actually have something due today; otherwise
    // whichever one does gets full weight.
    let productivityScore;
    if (totalTasksToday === 0 && totalHabitsToday === 0) {
      productivityScore = 0;
    } else {
      const taskScore  = totalTasksToday  > 0 ? tasksDoneToday  / totalTasksToday  : 0;
      const habitScore = totalHabitsToday > 0 ? habitsDoneToday / totalHabitsToday : 0;
      if (totalTasksToday === 0) {
        productivityScore = Math.round(habitScore * 100);
      } else if (totalHabitsToday === 0) {
        productivityScore = Math.round(taskScore * 100);
      } else {
        productivityScore = Math.round((taskScore * 0.6 + habitScore * 0.4) * 100);
      }
    }

    // Streak now comes from syncStreakShields (not a plain getOverallStreak
    // call) — it also opportunistically spends an available shield to
    // cover a missed day and grants new shields at 7-day milestones,
    // both idempotent so running this on every dashboard load is safe.
    const shieldState = await syncStreakShields(userId);

    // ── Weekly recap — a short narrative digest, not another chart.
    // Analytics already has detailed 8-week bar/line charts for this
    // same underlying data; this is the "did I have a good week" glance
    // version, meant to be read in 2 seconds on the Dashboard rather than
    // studied. This-week vs last-week keeps the one-line takeaway
    // genuinely comparative instead of a number with no context.
    const [tasksThisWeek, tasksLastWeek, flowThisWeek, flowLastWeek, moodThisWeek] = await Promise.all([
      db.execute({ sql: `SELECT COUNT(*) c FROM tasks WHERE user_id=? AND status='done' AND date(completed_at) >= date('now','-6 days')`, args: [userId] }),
      db.execute({ sql: `SELECT COUNT(*) c FROM tasks WHERE user_id=? AND status='done' AND date(completed_at) BETWEEN date('now','-13 days') AND date('now','-7 days')`, args: [userId] }),
      db.execute({ sql: `SELECT COALESCE(SUM(duration_minutes),0) m FROM focus_sessions WHERE user_id=? AND date(completed_at) >= date('now','-6 days')`, args: [userId] }),
      db.execute({ sql: `SELECT COALESCE(SUM(duration_minutes),0) m FROM focus_sessions WHERE user_id=? AND date(completed_at) BETWEEN date('now','-13 days') AND date('now','-7 days')`, args: [userId] }),
      db.execute({ sql: `SELECT AVG(mood) m FROM moods WHERE user_id=? AND date >= date('now','-6 days')`, args: [userId] }),
    ]);
    const recap = {
      tasksThisWeek:  Number(tasksThisWeek.rows[0].c),
      tasksLastWeek:  Number(tasksLastWeek.rows[0].c),
      flowMinutesThisWeek: Number(flowThisWeek.rows[0].m),
      flowMinutesLastWeek: Number(flowLastWeek.rows[0].m),
      avgMoodThisWeek: moodThisWeek.rows[0].m != null ? Math.round(Number(moodThisWeek.rows[0].m) * 10) / 10 : null,
      streak: shieldState.streak,
    };

    res.json({
      todaysTasks:       todaysTasksResult.rows,
      todaysHabits,
      upcomingDeadlines: upcomingResult.rows,
      nextMilestones:    nextMilestonesResult.rows,
      birthday:          birthdayResult.rows[0] || null,
      mood:              moodResult.rows[0] || null,
      quote:             quoteOfTheDay(),
      productivityScore,
      streak:            shieldState.streak,
      streakShields:     shieldState.shields,
      justShielded:      shieldState.justShielded,
      justEarnedShield:  shieldState.justEarnedShield,
      recap,
      treeStage: await getTreeStage(userId),
      level:     await getLevelInfo(userId),
      counts: { tasksDoneToday, totalTasksToday, habitsDoneToday, totalHabits: habits.length },
    });
  } catch (err) { console.error(err); res.status(500).json({ error: 'Database error' }); }
});

module.exports = router;