const express = require('express');
const router  = express.Router();
const { db }  = require('../db/connection');
const { addXp, evaluateAchievements } = require('../lib/gamification');

// ── Next recurrence date ───────────────────────────────────────
function nextRecurrenceDate(recurrence, fromDate) {
  const base = fromDate ? new Date(fromDate) : new Date();
  base.setHours(0, 0, 0, 0);

  if (recurrence === 'daily') {
    base.setDate(base.getDate() + 1);
  } else if (recurrence === 'weekly') {
    base.setDate(base.getDate() + 7);
  } else if (recurrence === 'monthly') {
    base.setMonth(base.getMonth() + 1);
  } else if (recurrence?.startsWith('custom:')) {
    const raw  = recurrence.split(':')[1] || '';
    const days = raw.split(',').map(Number).filter((n) => !isNaN(n)).sort((a, b) => a - b);

    if (!days.length) {
      base.setDate(base.getDate() + 1);
    } else {
      const today = base.getDay(); // 0 = Sun … 6 = Sat
      let next = days.find((d) => d > today);
      if (next === undefined) next = days[0];
      const add = next > today ? next - today : 7 - today + next;
      base.setDate(base.getDate() + add);
    }
  }

  return base.toISOString().slice(0, 10);
}

// ── GET /tasks ─────────────────────────────────────────────────
// Tasks generated by a project's "Break into tasks" carry a project_id
// and are meant to live only on that project's card — the general
// Tasks page and Dashboard should never show them. Projects.jsx needs
// the full set (its own tasks + everyone else's, to filter per-card),
// so it passes ?scope=all to opt back in.
router.get('/', async (req, res) => {
  try {
    const includeProjectTasks = req.query.scope === 'all';
    const sql = includeProjectTasks
      ? `SELECT * FROM tasks WHERE user_id = ? ORDER BY position ASC, created_at DESC`
      : `SELECT * FROM tasks WHERE user_id = ? AND project_id IS NULL ORDER BY position ASC, created_at DESC`;
    const result = await db.execute({ sql, args: [req.user.id] });
    res.json(result.rows);
  } catch (err) {
    console.error('GET /tasks error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

// ── POST /tasks ────────────────────────────────────────────────
router.post('/', async (req, res) => {
  try {
    const {
      title, description = '', priority = 'medium',
      category = 'general', deadline = null,
      deadline_time = null, recurrence = null,
      project_id = null,
    } = req.body;

    if (!title?.trim()) return res.status(400).json({ error: 'Title is required' });

    const maxPos = await db.execute({
      sql:  `SELECT COALESCE(MAX(position), -1) m FROM tasks WHERE user_id = ? AND status = 'todo'`,
      args: [req.user.id],
    });

    const insert = await db.execute({
      sql:  `INSERT INTO tasks
               (user_id, title, description, priority, category,
                deadline, deadline_time, recurrence, status, progress, position, project_id)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'todo', 0, ?, ?)`,
      args: [
        req.user.id, title.trim(), description, priority, category,
        deadline || null, deadline_time || null, recurrence || null,
        Number(maxPos.rows[0].m) + 1, project_id || null,
      ],
    });

    const task = (await db.execute({
      sql:  `SELECT * FROM tasks WHERE id = ? AND user_id = ?`,
      args: [Number(insert.lastInsertRowid), req.user.id],
    })).rows[0];

    res.status(201).json(task);
  } catch (err) {
    console.error('POST /tasks error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

// ── PUT /tasks/:id ─────────────────────────────────────────────
// Hardened: only whitelisted fields are merged, empty strings are
// normalized to NULL, numbers are coerced, and the real failure
// reason is both logged and returned so the client toast shows it.
const UPDATABLE = [
  'title', 'description', 'priority', 'category',
  'deadline', 'deadline_time', 'recurrence',
  'status', 'progress', 'position',
];
const NULLABLE = new Set(['deadline', 'deadline_time', 'recurrence']);

router.put('/:id', async (req, res) => {
  try {
    const existing = (await db.execute({
      sql:  `SELECT * FROM tasks WHERE id = ? AND user_id = ?`,
      args: [req.params.id, req.user.id],
    })).rows[0];
    if (!existing) return res.status(404).json({ error: 'Task not found' });

    // Build a clean patch from the request body
    const patch = {};
    for (const key of UPDATABLE) {
      if (!(key in (req.body || {}))) continue;
      let value = req.body[key];
      if (value === undefined) continue;                       // libSQL rejects undefined
      if (value === '' && NULLABLE.has(key)) value = null;     // '' → NULL for optional cols
      patch[key] = value;
    }

    if ('title' in patch) {
      if (typeof patch.title !== 'string' || !patch.title.trim())
        return res.status(400).json({ error: 'Title cannot be empty' });
      patch.title = patch.title.trim();
    }

    const updates   = { ...existing, ...patch };
    const wasDone   = existing.status === 'done';
    const isNowDone = updates.status  === 'done';

    updates.progress = Number(updates.progress) || 0;
    updates.position = Number(updates.position) || 0;
    if (isNowDone && updates.progress < 100) updates.progress = 100;
    updates.completed_at = isNowDone
      ? (existing.completed_at || new Date().toISOString())
      : null;

    await db.execute({
      sql:  `UPDATE tasks
             SET title=?, description=?, priority=?, category=?,
                 deadline=?, deadline_time=?, recurrence=?,
                 status=?, progress=?, position=?, completed_at=?
             WHERE id = ? AND user_id = ?`,
      args: [
        updates.title, updates.description ?? '', updates.priority, updates.category,
        updates.deadline ?? null, updates.deadline_time ?? null, updates.recurrence ?? null,
        updates.status, updates.progress, updates.position, updates.completed_at,
        req.params.id, req.user.id,
      ],
    });

    let xpAwarded = 0;
    let nextTask  = null;

    if (!wasDone && isNowDone) {
      // Gamification must never break a task save
      try {
        await addXp(req.user.id, 20, `Completed task: ${updates.title}`);
        xpAwarded = 20;
      } catch (e) {
        console.error('addXp failed (non-fatal):', e.message);
      }

      // ── Auto-create next occurrence ──────────────────────────
      if (updates.recurrence) {
        const nextDeadline = nextRecurrenceDate(updates.recurrence, updates.deadline);

        const maxPos = await db.execute({
          sql:  `SELECT COALESCE(MAX(position), -1) m FROM tasks WHERE user_id = ? AND status = 'todo'`,
          args: [req.user.id],
        });

        const nextInsert = await db.execute({
          sql:  `INSERT INTO tasks
                   (user_id, title, description, priority, category,
                    deadline, deadline_time, recurrence, status, progress, position)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'todo', 0, ?)`,
          args: [
            req.user.id,
            updates.title, updates.description ?? '', updates.priority, updates.category,
            nextDeadline, updates.deadline_time ?? null, updates.recurrence,
            Number(maxPos.rows[0].m) + 1,
          ],
        });

        nextTask = (await db.execute({
          sql:  `SELECT * FROM tasks WHERE id = ?`,
          args: [Number(nextInsert.lastInsertRowid)],
        })).rows[0];
      }
    }

    // This was the source of the "SQLITE_CONSTRAINT: FOREIGN KEY" error:
    // user_achievements.key references achievements(key), and if the
    // achievements catalogue isn't seeded, the insert fails and used to
    // take the whole save down with it. Now it's non-fatal.
    let unlocked = [];
    try {
      unlocked = await evaluateAchievements(req.user.id);
    } catch (e) {
      console.error('evaluateAchievements failed (non-fatal):', e.message);
    }

    const task = (await db.execute({
      sql:  `SELECT * FROM tasks WHERE id = ? AND user_id = ?`,
      args: [req.params.id, req.user.id],
    })).rows[0];

    res.json({ task, xpAwarded, unlocked, nextTask });
  } catch (err) {
    // Log full detail server-side AND return the message so the
    // client toast shows the real reason instead of a generic one.
    console.error(`PUT /tasks/${req.params.id} error:`, err);
    console.error('  → request body was:', JSON.stringify(req.body));
    res.status(500).json({ error: err.message || 'Database error' });
  }
});

// ── DELETE /tasks/:id ──────────────────────────────────────────
router.delete('/:id', async (req, res) => {
  try {
    const result = await db.execute({
      sql:  `DELETE FROM tasks WHERE id = ? AND user_id = ?`,
      args: [req.params.id, req.user.id],
    });
    if (result.rowsAffected === 0) return res.status(404).json({ error: 'Task not found' });
    res.status(204).end();
  } catch (err) {
    console.error('DELETE /tasks error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

// ── POST /tasks/reorder ────────────────────────────────────────
router.post('/reorder', async (req, res) => {
  try {
    const { tasks } = req.body;
    if (!Array.isArray(tasks)) return res.status(400).json({ error: 'tasks array required' });
    await db.batch(
      tasks.map((t) => ({
        sql:  `UPDATE tasks SET status = ?, position = ? WHERE id = ? AND user_id = ?`,
        args: [t.status, t.position, t.id, req.user.id],
      })),
      'write'
    );
    res.json({ ok: true });
  } catch (err) {
    console.error('POST /tasks/reorder error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

module.exports = router;