const express = require('express');
const router  = express.Router();
const { db }  = require('../db/connection');
const { addXp, evaluateAchievements, ACHIEVEMENTS } = require('../lib/gamification');
const { awardChannelPoints, CHANNEL_TASK_POINTS } = require('../lib/channelPoints');

// ── Next recurrence date ───────────────────────────────────────
function nextRecurrenceDate(recurrence, fromDate) {
  const base = fromDate ? new Date(fromDate) : new Date();
  base.setHours(0, 0, 0, 0);

  if (recurrence === 'daily') {
    base.setDate(base.getDate() + 1);
  } else if (recurrence === 'weekly') {
    base.setDate(base.getDate() + 7);
  } else if (recurrence === 'monthly') {
    base.setMonth(base.getMonth() + 1);
  } else if (recurrence === 'yearly') {
    // setFullYear alone mishandles Feb 29 — JS Date auto-normalizes a
    // nonexistent Feb 29 into Mar 1, silently drifting the date by a
    // day every non-leap year. Same leap-year guard used for birthdays
    // in notifications.js's rollForwardBirthdays/ensureBirthdayTask.
    const isLeap = (y) => (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0;
    const nextYear = base.getFullYear() + 1;
    if (base.getMonth() === 1 && base.getDate() === 29 && !isLeap(nextYear)) {
      base.setFullYear(nextYear, 1, 28);
    } else {
      base.setFullYear(nextYear);
    }
  } else if (recurrence?.startsWith('custom:')) {
    const raw  = recurrence.split(':')[1] || '';
    const days = raw.split(',').map(Number).filter((n) => !isNaN(n)).sort((a, b) => a - b);

    if (!days.length) {
      base.setDate(base.getDate() + 1);
    } else {
      const today = base.getDay(); // 0 = Sun … 6 = Sat
      let next = days.find((d) => d > today);
      if (next === undefined) next = days[0];
      const add = next > today ? next - today : 7 - today + next;
      base.setDate(base.getDate() + add);
    }
  }

  return base.toISOString().slice(0, 10);
}

// ── GET /tasks ─────────────────────────────────────────────────
// Tasks generated by a project's "Break into tasks" carry a project_id
// and are meant to live only on that project's card — the general
// Tasks page and Dashboard should never show them. Projects.jsx needs
// the full set (its own tasks + everyone else's, to filter per-card),
// so it passes ?scope=all to opt back in.
router.get('/', async (req, res) => {
  try {
    const includeProjectTasks = req.query.scope === 'all';
    const sql = includeProjectTasks
      ? `SELECT * FROM tasks WHERE user_id = ? ORDER BY position ASC, created_at DESC`
      : `SELECT * FROM tasks WHERE user_id = ? AND project_id IS NULL ORDER BY position ASC, created_at DESC`;
    const result = await db.execute({ sql, args: [req.user.id] });
    res.json(result.rows);
  } catch (err) {
    console.error('GET /tasks error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

// ── GET /tasks/:id ─────────────────────────────────────────────
// Single-task lookup — used by the Focus timer to re-hydrate a linked
// task's real cumulative time_spent_minutes (e.g. after a page refresh
// restores taskId from session storage but has no way to know the
// actual total without asking the server).
router.get('/:id', async (req, res) => {
  try {
    const row = (await db.execute({
      sql: `SELECT * FROM tasks WHERE id = ? AND user_id = ?`,
      args: [req.params.id, req.user.id],
    })).rows[0];
    if (!row) return res.status(404).json({ error: 'Task not found' });
    res.json(row);
  } catch (err) {
    console.error('GET /tasks/:id error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

// ── POST /tasks ────────────────────────────────────────────────
router.post('/', async (req, res) => {
  try {
    const {
      title, description = '', priority = 'medium',
      category = 'general', deadline = null,
      deadline_time = null, recurrence = null,
      project_id = null, remind_offsets_min = null,
      is_birthday = false, recurrence_until = null,
    } = req.body;

    if (!title?.trim()) return res.status(400).json({ error: 'Title is required' });

    const maxPos = await db.execute({
      sql:  `SELECT COALESCE(MAX(position), -1) m FROM tasks WHERE user_id = ? AND status = 'todo'`,
      args: [req.user.id],
    });

    // remind_offsets_min: array of minutes-before-deadline for the
    // "due soon" notification (see notifications.js) — e.g. [1440, 15]
    // for "1 day and 15 minutes before". null/omitted just means "use
    // the standard 1-hour-before default", nothing to store.
    const remindOffsetsJson = Array.isArray(remind_offsets_min) && remind_offsets_min.length
      ? JSON.stringify(remind_offsets_min.map(Number).filter((n) => Number.isFinite(n) && n >= 0))
      : null;

    const insert = await db.execute({
      sql:  `INSERT INTO tasks
               (user_id, title, description, priority, category,
                deadline, deadline_time, recurrence, status, progress, position, project_id, remind_offsets_min, is_birthday, recurrence_until)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'todo', 0, ?, ?, ?, ?, ?)`,
      args: [
        req.user.id, title.trim(), description, priority, category,
        deadline || null, deadline_time || null, recurrence || null,
        Number(maxPos.rows[0].m) + 1, project_id || null, remindOffsetsJson,
        is_birthday ? 1 : 0,
        // Only meaningful alongside an actual recurrence — a one-off
        // task ignoring a stray recurrence_until in the body is safer
        // than accidentally storing one that nothing ever reads.
        recurrence ? (recurrence_until || null) : null,
      ],
    });

    const task = (await db.execute({
      sql:  `SELECT * FROM tasks WHERE id = ? AND user_id = ?`,
      args: [Number(insert.lastInsertRowid), req.user.id],
    })).rows[0];

    res.status(201).json(task);
  } catch (err) {
    console.error('POST /tasks error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

// ── PUT /tasks/:id ─────────────────────────────────────────────
// Hardened: only whitelisted fields are merged, empty strings are
// normalized to NULL, numbers are coerced, and the real failure
// reason is both logged and returned so the client toast shows it.
const UPDATABLE = [
  'title', 'description', 'priority', 'category',
  'deadline', 'deadline_time', 'recurrence', 'recurrence_until',
  'status', 'progress', 'position',
];
const NULLABLE = new Set(['deadline', 'deadline_time', 'recurrence', 'recurrence_until']);

router.put('/:id', async (req, res) => {
  try {
    const existing = (await db.execute({
      sql:  `SELECT * FROM tasks WHERE id = ? AND user_id = ?`,
      args: [req.params.id, req.user.id],
    })).rows[0];
    if (!existing) return res.status(404).json({ error: 'Task not found' });

    // Build a clean patch from the request body
    const patch = {};
    for (const key of UPDATABLE) {
      if (!(key in (req.body || {}))) continue;
      let value = req.body[key];
      if (value === undefined) continue;                       // libSQL rejects undefined
      if (value === '' && NULLABLE.has(key)) value = null;     // '' → NULL for optional cols
      patch[key] = value;
    }

    if ('title' in patch) {
      if (typeof patch.title !== 'string' || !patch.title.trim())
        return res.status(400).json({ error: 'Title cannot be empty' });
      patch.title = patch.title.trim();
    }

    const updates   = { ...existing, ...patch };
    const wasDone   = existing.status === 'done';
    const isNowDone = updates.status  === 'done';

    updates.progress = Number(updates.progress) || 0;
    updates.position = Number(updates.position) || 0;
    if (isNowDone && updates.progress < 100) updates.progress = 100;
    updates.completed_at = isNowDone
      ? (existing.completed_at || new Date().toISOString())
      : null;
    // Unlike completed_at, this is never cleared — it's the permanent
    // record of "has this task ever paid out XP", so undoing and
    // re-doing the same task can't be used to farm XP repeatedly.
    const alreadyEarnedXp = Boolean(existing.first_completed_at);
    updates.first_completed_at = isNowDone
      ? (existing.first_completed_at || new Date().toISOString())
      : (existing.first_completed_at || null);

    // remind_offsets_min isn't in UPDATABLE — it's stored as a JSON
    // string but arrives from the client as a real array, so it needs
    // its own conversion rather than the generic passthrough merge
    // above (which would otherwise overwrite the stored JSON string
    // with a raw array object). Only touched when the request actually
    // includes the field; omitting it entirely leaves whatever was
    // already saved untouched.
    let remindOffsetsMin = existing.remind_offsets_min;
    if ('remind_offsets_min' in (req.body || {})) {
      const raw = req.body.remind_offsets_min;
      remindOffsetsMin = Array.isArray(raw) && raw.length
        ? JSON.stringify(raw.map(Number).filter((n) => Number.isFinite(n) && n >= 0))
        : null;
    }

    await db.execute({
      sql:  `UPDATE tasks
             SET title=?, description=?, priority=?, category=?,
                 deadline=?, deadline_time=?, recurrence=?, recurrence_until=?,
                 status=?, progress=?, position=?, completed_at=?, first_completed_at=?,
                 remind_offsets_min=?
             WHERE id = ? AND user_id = ?`,
      args: [
        updates.title, updates.description ?? '', updates.priority, updates.category,
        updates.deadline ?? null, updates.deadline_time ?? null, updates.recurrence ?? null,
        updates.recurrence ? (updates.recurrence_until ?? null) : null,
        updates.status, updates.progress, updates.position, updates.completed_at, updates.first_completed_at,
        remindOffsetsMin,
        req.params.id, req.user.id,
      ],
    });

    let xpAwarded = 0;
    let nextTask  = null;
    let late      = false;

    if (!wasDone && isNowDone) {
      // Gamification must never break a task save
      if (!alreadyEarnedXp) {
        // Late = completed on a local calendar day after the deadline
        // day, mirroring exactly what the "Overdue" badge already means
        // everywhere else in the app (TaskColumn on the Dashboard,
        // TaskGroup's "Overdue" section on Tasks.jsx) — a task finished
        // any time on its own due date still counts as on-time, only the
        // day after does not. Uses the same real-UTC→local-calendar-day
        // conversion as focus.js's localDay() (see comment there), fed
        // by tz_offset_min — the user's own browser offset, refreshed on
        // every notification-bell poll (routes/notifications.js) — so
        // this doesn't reintroduce the UTC-vs-local mismatch the mood
        // endpoint had. A user who has never opened the bell yet (offset
        // still NULL) just falls back to UTC "today", same as every
        // other date-sensitive endpoint in this codebase already does.
        if (updates.deadline) {
          try {
            const userRow = (await db.execute({
              sql:  `SELECT tz_offset_min FROM users WHERE id = ?`,
              args: [req.user.id],
            })).rows[0];
            const tzOffsetMin = Number(userRow?.tz_offset_min) || 0;
            const localToday  = new Date(Date.now() - tzOffsetMin * 60000).toISOString().slice(0, 10);
            late = localToday > updates.deadline;
          } catch (e) {
            console.error('late-task check failed (non-fatal, treated as on-time):', e.message);
          }
        }

        const xpAmount = late ? 10 : 20;
        try {
          await addXp(req.user.id, xpAmount, late
            ? `Completed task late: ${updates.title}`
            : `Completed task: ${updates.title}`);
          xpAwarded = xpAmount;
        } catch (e) {
          console.error('addXp failed (non-fatal):', e.message);
        }

        // Channel points — a separate, channel-scoped scoreboard (see
        // lib/channelPoints.js). Only fires for tasks an instructor
        // assigned through a channel (existing.channel_id set); a
        // student's own self-created tasks never touch this table.
        // Gated behind the same !alreadyEarnedXp flag as XP above so
        // toggling done/undone/done can't farm channel points either.
        // Halved on the same late/on-time basis as the XP award above.
        if (existing.channel_id) {
          try {
            const channelAmount = late ? Math.round(CHANNEL_TASK_POINTS / 2) : CHANNEL_TASK_POINTS;
            await awardChannelPoints(existing.channel_id, req.user.id, channelAmount, late
              ? `Completed task late: ${updates.title}`
              : `Completed task: ${updates.title}`);
          } catch (e) {
            console.error('awardChannelPoints failed (non-fatal):', e.message);
          }
        }
      }

      // ── Auto-create next occurrence ──────────────────────────
      // Gated behind !alreadyEarnedXp too — otherwise toggling a
      // recurring task done/undone/done would spawn a duplicate
      // "next occurrence" row every time, not just XP.
      // Also excludes is_birthday: birthdays have no "mark done" control
      // on the client (see Tasks.jsx/Calendar.jsx), but nothing stops a
      // birthday task from being marked done via some other surface that
      // lists all tasks generically (e.g. Focus's task picker) — without
      // this guard that would spawn a second row for next year on top of
      // the one rollForwardBirthdays (notifications.js) already rolls
      // forward in place, permanently duplicating that person's birthday.
      if (updates.recurrence && !alreadyEarnedXp && !updates.is_birthday) {
        const nextDeadline = nextRecurrenceDate(updates.recurrence, updates.deadline);

        // Optional cutoff (see tasks.recurrence_until migration) — a
        // plain string compare is safe since both sides are always
        // YYYY-MM-DD. Past it, the chain simply stops here instead of
        // spawning a next occurrence: no new row, nextTask stays null,
        // same as a non-recurring task being completed normally.
        const pastCutoff = updates.recurrence_until && nextDeadline > updates.recurrence_until;

        if (!pastCutoff) {
          const maxPos = await db.execute({
            sql:  `SELECT COALESCE(MAX(position), -1) m FROM tasks WHERE user_id = ? AND status = 'todo'`,
            args: [req.user.id],
          });

          const nextInsert = await db.execute({
            sql:  `INSERT INTO tasks
                     (user_id, title, description, priority, category,
                      deadline, deadline_time, recurrence, recurrence_until, status, progress, position)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'todo', 0, ?)`,
            args: [
              req.user.id,
              updates.title, updates.description ?? '', updates.priority, updates.category,
              nextDeadline, updates.deadline_time ?? null, updates.recurrence, updates.recurrence_until ?? null,
              Number(maxPos.rows[0].m) + 1,
            ],
          });

          nextTask = (await db.execute({
            sql:  `SELECT * FROM tasks WHERE id = ?`,
            args: [Number(nextInsert.lastInsertRowid)],
          })).rows[0];
        }
      }
    }

    const task = (await db.execute({
      sql:  `SELECT * FROM tasks WHERE id = ? AND user_id = ?`,
      args: [req.params.id, req.user.id],
    })).rows[0];

    // Respond now — everything below used to run and be AWAITED before
    // this response went out on every single save (not just
    // completions): a streak recalculation (2 unbounded table scans) +
    // 2 more count queries + up to 5 sequential achievement-lookup
    // queries, on every task edit, most of which don't even touch
    // completion status. That chain of DB round trips inside the
    // request/response cycle is what made the checkbox and the "+20 XP"
    // toast feel slow — the toast only fires client-side once this
    // response resolves, so it was waiting on all of that for no reason
    // most of the time.
    res.json({ task, xpAwarded, nextTask, unlocked: [], late });

    // Only evaluate achievements on an actual todo→done transition —
    // that's the only time these counts can move. A rename/reschedule/
    // category change has nothing to do with achievements and used to
    // pay this same cost for no reason.
    if (!wasDone && isNowDone) {
      evaluateAchievements(req.user.id)
        .then(async (unlocked) => {
          if (!unlocked.length) return;
          // Achievement unlocks now surface through the notification
          // bell instead of an inline toast on the completion response
          // — the bell already polls, and this keeps the common case
          // (every completion) fast without losing the rare case
          // (unlocking something) entirely.
          for (const key of unlocked) {
            const meta = ACHIEVEMENTS.find((a) => a.key === key);
            if (!meta) continue;
            try {
              await db.execute({
                sql:  `INSERT INTO notifications (user_id, type, title, body, link, dedupe_key, data)
                       VALUES (?, 'achievement_unlocked', ?, ?, NULL, ?, ?)
                       ON CONFLICT(user_id, dedupe_key) DO NOTHING`,
                args: [
                  req.user.id,
                  `🏆 ${meta.title}`,
                  meta.description,
                  `achievement:${key}:${req.user.id}`,
                  JSON.stringify({ key }),
                ],
              });
            } catch (e) {
              console.error('achievement notification insert failed (non-fatal):', e.message);
            }
          }
        })
        // This was already non-fatal to the save before (the FK-seeding
        // bug this comment used to describe) — still true, just running
        // after the response now instead of before it.
        .catch((e) => console.error('evaluateAchievements failed (non-fatal):', e.message));
    }
  } catch (err) {
    // Log full detail server-side AND return the message so the
    // client toast shows the real reason instead of a generic one.
    console.error(`PUT /tasks/${req.params.id} error:`, err);
    console.error('  → request body was:', JSON.stringify(req.body));
    res.status(500).json({ error: err.message || 'Database error' });
  }
});

// ── DELETE /tasks/:id ──────────────────────────────────────────
router.delete('/:id', async (req, res) => {
  try {
    const result = await db.execute({
      sql:  `DELETE FROM tasks WHERE id = ? AND user_id = ?`,
      args: [req.params.id, req.user.id],
    });
    if (result.rowsAffected === 0) return res.status(404).json({ error: 'Task not found' });
    res.status(204).end();
  } catch (err) {
    console.error('DELETE /tasks error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

// ── POST /tasks/reorder ────────────────────────────────────────
router.post('/reorder', async (req, res) => {
  try {
    const { tasks } = req.body;
    if (!Array.isArray(tasks)) return res.status(400).json({ error: 'tasks array required' });
    await db.batch(
      tasks.map((t) => ({
        sql:  `UPDATE tasks SET status = ?, position = ? WHERE id = ? AND user_id = ?`,
        args: [t.status, t.position, t.id, req.user.id],
      })),
      'write'
    );
    res.json({ ok: true });
  } catch (err) {
    console.error('POST /tasks/reorder error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

module.exports = router;